### ISSUE TITLE
tinycom breaks on qt5 dialogs

### ISSUE THREAD

**Issue by jan-harm** [digitalpeer/tinycom#1]
Tinycom seems to start ok (I use QT5 on linux mint) when opening the about box it breaks
(other dialog seem to do the same)
Traceback (most recent call last):
  File "/home/janharm/anaconda3/lib/python3.6/site-packages/tinycom/tinycom.py", line 361, in on_about
    msg = QtGui.QMessageBox(self)
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMessageBox'
Aborted (core dumped)

**Comment by digitalpeer** [comment]
Thanks.  Fixed by commit https://github.com/digitalpeer/tinycom/commit/f985078bdab6eeb18d97b452258bc470a01c0ba8
